import {
  calculateATRDrawChart,
  calculateMACD,
  calculateRSI,
  drawMACDIndicatorChart,
  drawRSIIndicatorChart,
  drawVortexIndicatorChart,
  calculateADX,
  calculateBBW,
  calculateVortex,
  calculateStochastic,
  calculateROC,
  calculateMomentum,
  calculateBBP,
  drawBBPIndicatorChart,
  calculateAwesomeOscillator,
  drawAwesomeOscillatorIndicator,
  calculateCCI,
  calculateAverageDayRange,
  calculateBalanceOfPower,
  calculateWilliamsR,
} from "../utility/indicatorsUtil";
export const indicatorConfig = {
  SMA: {
    color: "#FFA500",
    stroke: 1,
    period: 20,
    label: "Simple Moving Average",
    chartRequired: false,
  },
  EMA: {
    color: "#FF0000",
    stroke: 1,
    period: 20,
    label: "Expontential Moving Average",
    chartRequired: false,
  },
  ZigZag: {
    color: "#00FF00",
    label: "Zig Zag",
    deviation: 10,
    pivotLegs: 5,
    chartRequired: false,
  },
  RSI: {
    color: "#FFA500",
    stroke: 1,
    period: 14,
    label: "Relative Strength Index",
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateRSI,
  },
  MACD: {
    color: "#FFA500",
    stroke: 1,
    label: "Moving Average Convergence Divergence",
    fastPeriod: 12,
    slowPeriod: 26,
    signalPeriod: 9,
    chartRequired: true,
    drawChartFunction: drawMACDIndicatorChart,
    getChartData: calculateMACD,
  },
  ParabolicSAR: {
    color: "#FFA500",
    stroke: 2,
    label: "Parabolic SAR",
    acceleration: 0.02,
    maximum: 0.2,
    chartRequired: false,
  },
  BB: {
    color: "#FFA500",
    stroke: 1,
    label: "Bollinger Bands",
    period: 20,
    stdDev: 2,
    chartRequired: false,
  },
  BBW: {
    color: "#FFA500",
    stroke: 1,
    label: "Bollinger Bands Width",
    period: 20,
    stdDev: 2,
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateBBW,
  },
  KeltnerChannels: {
    color: "#FFA500",
    stroke: 2,
    label: "Keltner Channels",
    period: 20,
    multiplier: 2,
    chartRequired: false,
  },
  DonchainChannels: {
    color: "#FFA500",
    stroke: 2,
    label: "Donchain Channels",
    period: 20,
    chartRequired: false,
  },
  ATR: {
    color: "#FFA500",
    stroke: 1,
    label: "Average True Range",
    period: 20,
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateATRDrawChart,
  },
  ADX: {
    color: "#FFA500",
    stroke: 1,
    label: "Average Directional Index",
    period: 20,
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateADX,
  },
  Vortex: {
    color: "#FFA500",
    stroke: 1,
    label: "Vortex",
    period: 12,
    chartRequired: true,
    drawChartFunction: drawVortexIndicatorChart,
    getChartData: calculateVortex,
  },
  Alligator: {
    color: "#FFA500",
    stroke: 1,
    label: "Williams Alligator",
    jawPeriod: 13,
    teethPeriod: 8,
    lipsPeriod: 5,
    chartRequired: false,
  },
  Stochaistic: {
    color: "#FFA500",
    stroke: 1,
    label: "Stochaistic Oscillator",
    period: 14,
    smoothPeriod: 1,
    signalPeriod: 3,
    chartRequired: true,
    drawChartFunction: drawVortexIndicatorChart,
    getChartData: calculateStochastic,
  },
  ROC: {
    color: "#FFA500",
    stroke: 1,
    label: "Rate of Change",
    period: 20,
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateROC,
  },
  Momentum: {
    color: "#FFA500",
    stroke: 1,
    label: "Momentum",
    period: 20,
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateMomentum,
  },
  BBP: {
    color: "#FFA500",
    stroke: 1,
    label: "Bull Bear Power",
    period: 12,
    chartRequired: true,
    drawChartFunction: drawBBPIndicatorChart,
    getChartData: calculateBBP,
  },
  Envelope: {
    color: "#FFA500",
    stroke: 1,
    label: "Envelope",
    period: 20,
    percentage: 10,
    chartRequired: false,
  },
  AwesomeOscillator: {
    color: "#FFA500",
    stroke: 1,
    label: "Awesome Oscillator",
    chartRequired: true,
    drawChartFunction: drawAwesomeOscillatorIndicator,
    getChartData: calculateAwesomeOscillator,
  },
  IchimokuCloud: {
    color: "#FFA500",
    stroke: 1,
    label: "Ichimoku Cloud",
    conversionPeriod: 9,
    basePeriod: 26,
    spanBPeriod: 52,
    laggingSpanPeriod: 26,
    chartRequired: false,
  },
  CCI: {
    color: "#FFA500",
    stroke: 1,
    label: "Commodity Channel Index",
    period: 20,
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateCCI,
  },
  SuperTrend: {
    color: "#FFA500",
    stroke: 1,
    label: "Super Trend",
    period: 10,
    multiplier: 3,
    chartRequired: false,
  },
  AverageDayRange: {
    color: "#FFA500",
    stroke: 1,
    label: "Average Day Range",
    period: 14,
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateAverageDayRange,
  },
  BalanceOfPower: {
    color: "#FFA500",
    stroke: 1,
    label: "Balance of Power",
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateBalanceOfPower,
  },
  WilliamsR: {
    color: "#FFA500",
    stroke: 1,
    label: "Williams %R",
    period: 14,
    chartRequired: true,
    drawChartFunction: drawRSIIndicatorChart,
    getChartData: calculateWilliamsR,
  },
  DoubleEMA: {
    color: "#FFA500",
    stroke: 1,
    period: 9,
    label: "Double Exponential Moving Average",
    chartRequired: false,
  },
  TripleEMA: {
    color: "#FFA500",
    stroke: 1,
    period: 9,
    label: "Triple Exponential Moving Average",
    chartRequired: false,
  },
};
